Problem: configuring psql target dbs
omnigres/omnigres pull request #418
Opened 2023-12-25 19:22 UTC by yrashk

Currently it's impossible to configure the databases `psql_` targets create. However, this is very limiting because sometimes we want to use them with a particular configuration.

Solution: use postgresql.conf and pg_hba.confi if provided

2023-12-25 20:48 UTC, viggy28 requested changes

2023-12-25 20:48 UTC, viggy28 commented on cmake/PostgreSQLExtension.cmake
> +    export PGHBACONF=\"${CMAKE_CURRENT_SOURCE_DIR}/postgresql.conf\"
shouldn't this be `pg_hba.conf`?

2023-12-25 20:58 UTC, yrashk commented on cmake/PostgreSQLExtension.cmake
> +    export PGHBACONF=\"${CMAKE_CURRENT_SOURCE_DIR}/postgresql.conf\"
It should be

2023-12-26 18:07 UTC, viggy28 approved these changes

2023-12-26 19:53 UTC, merged